namespace SbotControl.UI
{
    partial class BotInfoUC
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject1 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject2 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject3 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject4 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject5 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject6 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject7 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject8 = new DevExpress.Utils.SerializableAppearanceObject();
            this.dataLayoutControl1 = new DevExpress.XtraDataLayout.DataLayoutControl();
            this.rec = new DevExpress.XtraRichEdit.RichEditControl();
            this.beCommands = new DevExpress.XtraEditors.ButtonEdit();
            this.lblGoldPetHour = new DevExpress.XtraEditors.LabelControl();
            this.lblGoldLoop = new DevExpress.XtraEditors.LabelControl();
            this.lblItemDrops = new DevExpress.XtraEditors.LabelControl();
            this.lblDiedsess = new DevExpress.XtraEditors.LabelControl();
            this.lblDied = new DevExpress.XtraEditors.LabelControl();
            this.lblSPMin = new DevExpress.XtraEditors.LabelControl();
            this.lblSPH = new DevExpress.XtraEditors.LabelControl();
            this.lblSPGained = new DevExpress.XtraEditors.LabelControl();
            this.lblXPH = new DevExpress.XtraEditors.LabelControl();
            this.lblXPMin = new DevExpress.XtraEditors.LabelControl();
            this.lblXPGained = new DevExpress.XtraEditors.LabelControl();
            this.lblKills = new DevExpress.XtraEditors.LabelControl();
            this.lblTotaltime = new DevExpress.XtraEditors.LabelControl();
            this.lblLocationName = new DevExpress.XtraEditors.LabelControl();
            this.ceVisable = new DevExpress.XtraEditors.CheckEdit();
            this.peMPBar = new DevExpress.XtraEditors.PictureEdit();
            this.peHPBar = new DevExpress.XtraEditors.PictureEdit();
            this.lblSkillPoint = new DevExpress.XtraEditors.LabelControl();
            this.lblGold = new DevExpress.XtraEditors.LabelControl();
            this.lblLevel = new DevExpress.XtraEditors.LabelControl();
            this.lblPosY = new DevExpress.XtraEditors.LabelControl();
            this.lblPosX = new DevExpress.XtraEditors.LabelControl();
            this.lblConnectionQualityCur = new DevExpress.XtraEditors.LabelControl();
            this.lblConnectionQualityAvg = new DevExpress.XtraEditors.LabelControl();
            this.lblBotStatus = new DevExpress.XtraEditors.LabelControl();
            this.lblSilkroadServerStatus = new DevExpress.XtraEditors.LabelControl();
            this.lblGroup = new DevExpress.XtraEditors.LabelControl();
            this.lblCharName = new DevExpress.XtraEditors.LabelControl();
            this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGeneratedGroup0 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem3 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem4 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem5 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem6 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem7 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem8 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem9 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem10 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem11 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem14 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem11A = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem11B = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem16 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem17 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem18 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem19 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem20 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem21 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem22 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem23 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem24 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem15 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem25 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem25A = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem12 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem13 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem27 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem26 = new DevExpress.XtraLayout.LayoutControlItem();
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).BeginInit();
            this.dataLayoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.beCommands.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ceVisable.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.peMPBar.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.peHPBar.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGeneratedGroup0)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem9)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem11)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem14)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem11A)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem11B)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem16)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem17)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem18)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem19)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem20)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem21)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem22)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem23)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem24)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem15)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem25)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem25A)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem12)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem13)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem27)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem26)).BeginInit();
            this.SuspendLayout();
            // 
            // dataLayoutControl1
            // 
            this.dataLayoutControl1.Controls.Add(this.rec);
            this.dataLayoutControl1.Controls.Add(this.beCommands);
            this.dataLayoutControl1.Controls.Add(this.lblGoldPetHour);
            this.dataLayoutControl1.Controls.Add(this.lblGoldLoop);
            this.dataLayoutControl1.Controls.Add(this.lblItemDrops);
            this.dataLayoutControl1.Controls.Add(this.lblDiedsess);
            this.dataLayoutControl1.Controls.Add(this.lblDied);
            this.dataLayoutControl1.Controls.Add(this.lblSPMin);
            this.dataLayoutControl1.Controls.Add(this.lblSPH);
            this.dataLayoutControl1.Controls.Add(this.lblSPGained);
            this.dataLayoutControl1.Controls.Add(this.lblXPH);
            this.dataLayoutControl1.Controls.Add(this.lblXPMin);
            this.dataLayoutControl1.Controls.Add(this.lblXPGained);
            this.dataLayoutControl1.Controls.Add(this.lblKills);
            this.dataLayoutControl1.Controls.Add(this.lblTotaltime);
            this.dataLayoutControl1.Controls.Add(this.lblLocationName);
            this.dataLayoutControl1.Controls.Add(this.ceVisable);
            this.dataLayoutControl1.Controls.Add(this.peMPBar);
            this.dataLayoutControl1.Controls.Add(this.peHPBar);
            this.dataLayoutControl1.Controls.Add(this.lblSkillPoint);
            this.dataLayoutControl1.Controls.Add(this.lblGold);
            this.dataLayoutControl1.Controls.Add(this.lblLevel);
            this.dataLayoutControl1.Controls.Add(this.lblPosY);
            this.dataLayoutControl1.Controls.Add(this.lblPosX);
            this.dataLayoutControl1.Controls.Add(this.lblConnectionQualityCur);
            this.dataLayoutControl1.Controls.Add(this.lblConnectionQualityAvg);
            this.dataLayoutControl1.Controls.Add(this.lblBotStatus);
            this.dataLayoutControl1.Controls.Add(this.lblSilkroadServerStatus);
            this.dataLayoutControl1.Controls.Add(this.lblGroup);
            this.dataLayoutControl1.Controls.Add(this.lblCharName);
            this.dataLayoutControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataLayoutControl1.Location = new System.Drawing.Point(0, 0);
            this.dataLayoutControl1.Name = "dataLayoutControl1";
            this.dataLayoutControl1.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(683, 344, 401, 634);
            this.dataLayoutControl1.Root = this.layoutControlGroup1;
            this.dataLayoutControl1.Size = new System.Drawing.Size(800, 550);
            this.dataLayoutControl1.TabIndex = 0;
            this.dataLayoutControl1.Text = "dataLayoutControl1";
            // 
            // rec
            // 
            this.rec.ActiveViewType = DevExpress.XtraRichEdit.RichEditViewType.Simple;
            this.rec.EnableToolTips = true;
            this.rec.Location = new System.Drawing.Point(101, 12);
            this.rec.Name = "rec";
            this.rec.Options.Bookmarks.AllowNameResolution = false;
            this.rec.ReadOnly = true;
            this.rec.Size = new System.Drawing.Size(687, 492);
            this.rec.TabIndex = 32;
            this.rec.Views.SimpleView.AdjustColorsToSkins = true;
            this.rec.Views.SimpleView.AllowDisplayLineNumbers = true;
            this.rec.Views.SimpleView.BackColor = System.Drawing.Color.Black;
            // 
            // beCommands
            // 
            this.beCommands.Location = new System.Drawing.Point(69, 508);
            this.beCommands.Name = "beCommands";
            this.beCommands.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Glyph, "Start Game", -1, true, true, false, DevExpress.XtraEditors.ImageLocation.MiddleCenter, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject1, "", null, null, true),
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Glyph, "Go Clientless", -1, true, true, false, DevExpress.XtraEditors.ImageLocation.MiddleCenter, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject2, "", null, null, true),
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Glyph, "Disconnect", -1, true, true, false, DevExpress.XtraEditors.ImageLocation.MiddleCenter, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject3, "", null, null, true),
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Glyph, "Reset Stats", -1, true, true, false, DevExpress.XtraEditors.ImageLocation.MiddleCenter, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject4, "", null, null, true),
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Glyph, "Save Settings", -1, true, true, false, DevExpress.XtraEditors.ImageLocation.MiddleCenter, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject5, "", null, null, true),
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Glyph, "Show/Hide Client", -1, true, true, false, DevExpress.XtraEditors.ImageLocation.MiddleCenter, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject6, "", null, null, true),
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Glyph, "Start Training", -1, true, true, false, DevExpress.XtraEditors.ImageLocation.MiddleCenter, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject7, "", null, null, true),
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Glyph, "Stop Training", -1, true, true, false, DevExpress.XtraEditors.ImageLocation.MiddleCenter, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject8, "", null, null, true)});
            this.beCommands.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.HideTextEditor;
            this.beCommands.Size = new System.Drawing.Size(719, 20);
            this.beCommands.StyleController = this.dataLayoutControl1;
            this.beCommands.TabIndex = 31;
            this.beCommands.ButtonClick += new DevExpress.XtraEditors.Controls.ButtonPressedEventHandler(this.beCommands_ButtonClick);
            // 
            // lblGoldPetHour
            // 
            this.lblGoldPetHour.Location = new System.Drawing.Point(69, 491);
            this.lblGoldPetHour.Name = "lblGoldPetHour";
            this.lblGoldPetHour.Size = new System.Drawing.Size(28, 13);
            this.lblGoldPetHour.StyleController = this.dataLayoutControl1;
            this.lblGoldPetHour.TabIndex = 30;
            this.lblGoldPetHour.Text = "NONE";
            // 
            // lblGoldLoop
            // 
            this.lblGoldLoop.Location = new System.Drawing.Point(69, 474);
            this.lblGoldLoop.Name = "lblGoldLoop";
            this.lblGoldLoop.Size = new System.Drawing.Size(28, 13);
            this.lblGoldLoop.StyleController = this.dataLayoutControl1;
            this.lblGoldLoop.TabIndex = 29;
            this.lblGoldLoop.Text = "NONE";
            // 
            // lblItemDrops
            // 
            this.lblItemDrops.Location = new System.Drawing.Point(69, 457);
            this.lblItemDrops.Name = "lblItemDrops";
            this.lblItemDrops.Size = new System.Drawing.Size(28, 13);
            this.lblItemDrops.StyleController = this.dataLayoutControl1;
            this.lblItemDrops.TabIndex = 28;
            this.lblItemDrops.Text = "NONE";
            // 
            // lblDiedsess
            // 
            this.lblDiedsess.Location = new System.Drawing.Point(69, 440);
            this.lblDiedsess.Name = "lblDiedsess";
            this.lblDiedsess.Size = new System.Drawing.Size(28, 13);
            this.lblDiedsess.StyleController = this.dataLayoutControl1;
            this.lblDiedsess.TabIndex = 27;
            this.lblDiedsess.Text = "NONE";
            // 
            // lblDied
            // 
            this.lblDied.Location = new System.Drawing.Point(69, 423);
            this.lblDied.Name = "lblDied";
            this.lblDied.Size = new System.Drawing.Size(28, 13);
            this.lblDied.StyleController = this.dataLayoutControl1;
            this.lblDied.TabIndex = 26;
            this.lblDied.Text = "NONE";
            // 
            // lblSPMin
            // 
            this.lblSPMin.Location = new System.Drawing.Point(69, 389);
            this.lblSPMin.Name = "lblSPMin";
            this.lblSPMin.Size = new System.Drawing.Size(28, 13);
            this.lblSPMin.StyleController = this.dataLayoutControl1;
            this.lblSPMin.TabIndex = 25;
            this.lblSPMin.Text = "NONE";
            // 
            // lblSPH
            // 
            this.lblSPH.Location = new System.Drawing.Point(69, 406);
            this.lblSPH.Name = "lblSPH";
            this.lblSPH.Size = new System.Drawing.Size(28, 13);
            this.lblSPH.StyleController = this.dataLayoutControl1;
            this.lblSPH.TabIndex = 24;
            this.lblSPH.Text = "NONE";
            // 
            // lblSPGained
            // 
            this.lblSPGained.Location = new System.Drawing.Point(69, 372);
            this.lblSPGained.Name = "lblSPGained";
            this.lblSPGained.Size = new System.Drawing.Size(28, 13);
            this.lblSPGained.StyleController = this.dataLayoutControl1;
            this.lblSPGained.TabIndex = 23;
            this.lblSPGained.Text = "NONE";
            // 
            // lblXPH
            // 
            this.lblXPH.Location = new System.Drawing.Point(69, 355);
            this.lblXPH.Name = "lblXPH";
            this.lblXPH.Size = new System.Drawing.Size(28, 13);
            this.lblXPH.StyleController = this.dataLayoutControl1;
            this.lblXPH.TabIndex = 22;
            this.lblXPH.Text = "NONE";
            // 
            // lblXPMin
            // 
            this.lblXPMin.Location = new System.Drawing.Point(69, 338);
            this.lblXPMin.Name = "lblXPMin";
            this.lblXPMin.Size = new System.Drawing.Size(28, 13);
            this.lblXPMin.StyleController = this.dataLayoutControl1;
            this.lblXPMin.TabIndex = 21;
            this.lblXPMin.Text = "NONE";
            // 
            // lblXPGained
            // 
            this.lblXPGained.Location = new System.Drawing.Point(69, 321);
            this.lblXPGained.Name = "lblXPGained";
            this.lblXPGained.Size = new System.Drawing.Size(28, 13);
            this.lblXPGained.StyleController = this.dataLayoutControl1;
            this.lblXPGained.TabIndex = 20;
            this.lblXPGained.Text = "NONE";
            // 
            // lblKills
            // 
            this.lblKills.Location = new System.Drawing.Point(69, 304);
            this.lblKills.Name = "lblKills";
            this.lblKills.Size = new System.Drawing.Size(28, 13);
            this.lblKills.StyleController = this.dataLayoutControl1;
            this.lblKills.TabIndex = 19;
            this.lblKills.Text = "NONE";
            // 
            // lblTotaltime
            // 
            this.lblTotaltime.Location = new System.Drawing.Point(69, 287);
            this.lblTotaltime.Name = "lblTotaltime";
            this.lblTotaltime.Size = new System.Drawing.Size(28, 13);
            this.lblTotaltime.StyleController = this.dataLayoutControl1;
            this.lblTotaltime.TabIndex = 18;
            this.lblTotaltime.Text = "NONE";
            // 
            // lblLocationName
            // 
            this.lblLocationName.Location = new System.Drawing.Point(69, 270);
            this.lblLocationName.Name = "lblLocationName";
            this.lblLocationName.Size = new System.Drawing.Size(28, 13);
            this.lblLocationName.StyleController = this.dataLayoutControl1;
            this.lblLocationName.TabIndex = 17;
            this.lblLocationName.Text = "NONE";
            // 
            // ceVisable
            // 
            this.ceVisable.Location = new System.Drawing.Point(12, 77);
            this.ceVisable.Name = "ceVisable";
            this.ceVisable.Properties.Caption = "Visible";
            this.ceVisable.Size = new System.Drawing.Size(85, 19);
            this.ceVisable.StyleController = this.dataLayoutControl1;
            this.ceVisable.TabIndex = 16;
            // 
            // peMPBar
            // 
            this.peMPBar.Location = new System.Drawing.Point(12, 36);
            this.peMPBar.Name = "peMPBar";
            this.peMPBar.Properties.ShowCameraMenuItem = DevExpress.XtraEditors.Controls.CameraMenuItemVisibility.Auto;
            this.peMPBar.Size = new System.Drawing.Size(85, 20);
            this.peMPBar.StyleController = this.dataLayoutControl1;
            this.peMPBar.TabIndex = 15;
            // 
            // peHPBar
            // 
            this.peHPBar.Location = new System.Drawing.Point(12, 12);
            this.peHPBar.Name = "peHPBar";
            this.peHPBar.Properties.ShowCameraMenuItem = DevExpress.XtraEditors.Controls.CameraMenuItemVisibility.Auto;
            this.peHPBar.Size = new System.Drawing.Size(85, 20);
            this.peHPBar.StyleController = this.dataLayoutControl1;
            this.peHPBar.TabIndex = 14;
            // 
            // lblSkillPoint
            // 
            this.lblSkillPoint.Location = new System.Drawing.Point(69, 253);
            this.lblSkillPoint.Name = "lblSkillPoint";
            this.lblSkillPoint.Size = new System.Drawing.Size(28, 13);
            this.lblSkillPoint.StyleController = this.dataLayoutControl1;
            this.lblSkillPoint.TabIndex = 13;
            this.lblSkillPoint.Text = "NONE";
            // 
            // lblGold
            // 
            this.lblGold.Location = new System.Drawing.Point(69, 236);
            this.lblGold.Name = "lblGold";
            this.lblGold.Size = new System.Drawing.Size(28, 13);
            this.lblGold.StyleController = this.dataLayoutControl1;
            this.lblGold.TabIndex = 12;
            this.lblGold.Text = "NONE";
            // 
            // lblLevel
            // 
            this.lblLevel.Location = new System.Drawing.Point(69, 219);
            this.lblLevel.Name = "lblLevel";
            this.lblLevel.Size = new System.Drawing.Size(28, 13);
            this.lblLevel.StyleController = this.dataLayoutControl1;
            this.lblLevel.TabIndex = 11;
            this.lblLevel.Text = "NONE";
            // 
            // lblPosY
            // 
            this.lblPosY.Location = new System.Drawing.Point(69, 202);
            this.lblPosY.Name = "lblPosY";
            this.lblPosY.Size = new System.Drawing.Size(28, 13);
            this.lblPosY.StyleController = this.dataLayoutControl1;
            this.lblPosY.TabIndex = 10;
            this.lblPosY.Text = "NONE";
            // 
            // lblPosX
            // 
            this.lblPosX.Location = new System.Drawing.Point(69, 185);
            this.lblPosX.Name = "lblPosX";
            this.lblPosX.Size = new System.Drawing.Size(28, 13);
            this.lblPosX.StyleController = this.dataLayoutControl1;
            this.lblPosX.TabIndex = 9;
            this.lblPosX.Text = "NONE";
            // 
            // lblConnectionQualityCur
            // 
            this.lblConnectionQualityCur.Location = new System.Drawing.Point(69, 168);
            this.lblConnectionQualityCur.Name = "lblConnectionQualityCur";
            this.lblConnectionQualityCur.Size = new System.Drawing.Size(28, 13);
            this.lblConnectionQualityCur.StyleController = this.dataLayoutControl1;
            this.lblConnectionQualityCur.TabIndex = 8;
            this.lblConnectionQualityCur.Text = "NONE";
            // 
            // lblConnectionQualityAvg
            // 
            this.lblConnectionQualityAvg.Location = new System.Drawing.Point(69, 151);
            this.lblConnectionQualityAvg.Name = "lblConnectionQualityAvg";
            this.lblConnectionQualityAvg.Size = new System.Drawing.Size(28, 13);
            this.lblConnectionQualityAvg.StyleController = this.dataLayoutControl1;
            this.lblConnectionQualityAvg.TabIndex = 7;
            this.lblConnectionQualityAvg.Text = "NONE";
            // 
            // lblBotStatus
            // 
            this.lblBotStatus.Location = new System.Drawing.Point(69, 134);
            this.lblBotStatus.Name = "lblBotStatus";
            this.lblBotStatus.Size = new System.Drawing.Size(28, 13);
            this.lblBotStatus.StyleController = this.dataLayoutControl1;
            this.lblBotStatus.TabIndex = 6;
            this.lblBotStatus.Text = "NONE";
            // 
            // lblSilkroadServerStatus
            // 
            this.lblSilkroadServerStatus.Location = new System.Drawing.Point(69, 117);
            this.lblSilkroadServerStatus.Name = "lblSilkroadServerStatus";
            this.lblSilkroadServerStatus.Size = new System.Drawing.Size(28, 13);
            this.lblSilkroadServerStatus.StyleController = this.dataLayoutControl1;
            this.lblSilkroadServerStatus.TabIndex = 1;
            this.lblSilkroadServerStatus.Text = "NONE";
            // 
            // lblGroup
            // 
            this.lblGroup.Location = new System.Drawing.Point(69, 100);
            this.lblGroup.Name = "lblGroup";
            this.lblGroup.Size = new System.Drawing.Size(28, 13);
            this.lblGroup.StyleController = this.dataLayoutControl1;
            this.lblGroup.TabIndex = 5;
            this.lblGroup.Text = "NONE";
            // 
            // lblCharName
            // 
            this.lblCharName.Location = new System.Drawing.Point(69, 60);
            this.lblCharName.Name = "lblCharName";
            this.lblCharName.Size = new System.Drawing.Size(28, 13);
            this.lblCharName.StyleController = this.dataLayoutControl1;
            this.lblCharName.TabIndex = 4;
            this.lblCharName.Text = "NONE";
            // 
            // layoutControlGroup1
            // 
            this.layoutControlGroup1.CustomizationFormText = "Root";
            this.layoutControlGroup1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup1.GroupBordersVisible = false;
            this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGeneratedGroup0});
            this.layoutControlGroup1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup1.Name = "Root";
            this.layoutControlGroup1.Size = new System.Drawing.Size(800, 550);
            this.layoutControlGroup1.TextVisible = false;
            // 
            // autoGeneratedGroup0
            // 
            this.autoGeneratedGroup0.AllowDrawBackground = false;
            this.autoGeneratedGroup0.CustomizationFormText = "autoGeneratedGroup0";
            this.autoGeneratedGroup0.GroupBordersVisible = false;
            this.autoGeneratedGroup0.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem1,
            this.layoutControlItem2,
            this.layoutControlItem3,
            this.layoutControlItem4,
            this.layoutControlItem5,
            this.layoutControlItem6,
            this.layoutControlItem7,
            this.layoutControlItem8,
            this.layoutControlItem9,
            this.layoutControlItem10,
            this.layoutControlItem11,
            this.layoutControlItem14,
            this.layoutControlItem11A,
            this.layoutControlItem11B,
            this.layoutControlItem16,
            this.layoutControlItem17,
            this.layoutControlItem18,
            this.layoutControlItem19,
            this.layoutControlItem20,
            this.layoutControlItem21,
            this.layoutControlItem22,
            this.layoutControlItem23,
            this.layoutControlItem24,
            this.layoutControlItem15,
            this.layoutControlItem25,
            this.layoutControlItem25A,
            this.layoutControlItem12,
            this.layoutControlItem13,
            this.layoutControlItem27,
            this.layoutControlItem26});
            this.autoGeneratedGroup0.Location = new System.Drawing.Point(0, 0);
            this.autoGeneratedGroup0.Name = "autoGeneratedGroup0";
            this.autoGeneratedGroup0.Size = new System.Drawing.Size(780, 530);
            // 
            // layoutControlItem1
            // 
            this.layoutControlItem1.Control = this.lblCharName;
            this.layoutControlItem1.CustomizationFormText = "Name";
            this.layoutControlItem1.Location = new System.Drawing.Point(0, 48);
            this.layoutControlItem1.Name = "layoutControlItem1";
            this.layoutControlItem1.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem1.Text = "Name";
            this.layoutControlItem1.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem2
            // 
            this.layoutControlItem2.Control = this.lblGroup;
            this.layoutControlItem2.CustomizationFormText = "Group";
            this.layoutControlItem2.Location = new System.Drawing.Point(0, 88);
            this.layoutControlItem2.Name = "layoutControlItem2";
            this.layoutControlItem2.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem2.Text = "Group";
            this.layoutControlItem2.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem3
            // 
            this.layoutControlItem3.Control = this.lblSilkroadServerStatus;
            this.layoutControlItem3.CustomizationFormText = "Connection";
            this.layoutControlItem3.Location = new System.Drawing.Point(0, 105);
            this.layoutControlItem3.Name = "layoutControlItem3";
            this.layoutControlItem3.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem3.Text = "Connection";
            this.layoutControlItem3.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem4
            // 
            this.layoutControlItem4.Control = this.lblBotStatus;
            this.layoutControlItem4.CustomizationFormText = "Status";
            this.layoutControlItem4.Location = new System.Drawing.Point(0, 122);
            this.layoutControlItem4.Name = "layoutControlItem4";
            this.layoutControlItem4.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem4.Text = "Status";
            this.layoutControlItem4.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem5
            // 
            this.layoutControlItem5.Control = this.lblConnectionQualityAvg;
            this.layoutControlItem5.CustomizationFormText = "Avg";
            this.layoutControlItem5.Location = new System.Drawing.Point(0, 139);
            this.layoutControlItem5.Name = "layoutControlItem5";
            this.layoutControlItem5.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem5.Text = "Avg";
            this.layoutControlItem5.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem6
            // 
            this.layoutControlItem6.Control = this.lblConnectionQualityCur;
            this.layoutControlItem6.CustomizationFormText = "Cur";
            this.layoutControlItem6.Location = new System.Drawing.Point(0, 156);
            this.layoutControlItem6.Name = "layoutControlItem6";
            this.layoutControlItem6.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem6.Text = "Cur";
            this.layoutControlItem6.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem7
            // 
            this.layoutControlItem7.Control = this.lblPosX;
            this.layoutControlItem7.CustomizationFormText = "X";
            this.layoutControlItem7.Location = new System.Drawing.Point(0, 173);
            this.layoutControlItem7.Name = "layoutControlItem7";
            this.layoutControlItem7.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem7.Text = "X";
            this.layoutControlItem7.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem8
            // 
            this.layoutControlItem8.Control = this.lblPosY;
            this.layoutControlItem8.CustomizationFormText = "Y";
            this.layoutControlItem8.Location = new System.Drawing.Point(0, 190);
            this.layoutControlItem8.Name = "layoutControlItem8";
            this.layoutControlItem8.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem8.Text = "Y";
            this.layoutControlItem8.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem9
            // 
            this.layoutControlItem9.Control = this.lblLevel;
            this.layoutControlItem9.CustomizationFormText = "Level";
            this.layoutControlItem9.Location = new System.Drawing.Point(0, 207);
            this.layoutControlItem9.Name = "layoutControlItem9";
            this.layoutControlItem9.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem9.Text = "Level";
            this.layoutControlItem9.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem10
            // 
            this.layoutControlItem10.Control = this.lblGold;
            this.layoutControlItem10.CustomizationFormText = "Gold";
            this.layoutControlItem10.Location = new System.Drawing.Point(0, 224);
            this.layoutControlItem10.Name = "layoutControlItem10";
            this.layoutControlItem10.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem10.Text = "Gold";
            this.layoutControlItem10.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem11
            // 
            this.layoutControlItem11.Control = this.lblSkillPoint;
            this.layoutControlItem11.CustomizationFormText = "SP";
            this.layoutControlItem11.Location = new System.Drawing.Point(0, 241);
            this.layoutControlItem11.Name = "layoutControlItem11";
            this.layoutControlItem11.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem11.Text = "SP";
            this.layoutControlItem11.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem14
            // 
            this.layoutControlItem14.Control = this.ceVisable;
            this.layoutControlItem14.CustomizationFormText = "layoutControlItem14";
            this.layoutControlItem14.Location = new System.Drawing.Point(0, 65);
            this.layoutControlItem14.Name = "layoutControlItem14";
            this.layoutControlItem14.Size = new System.Drawing.Size(89, 23);
            this.layoutControlItem14.Text = "Visible Check";
            this.layoutControlItem14.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem14.TextVisible = false;
            // 
            // layoutControlItem11A
            // 
            this.layoutControlItem11A.Control = this.lblLocationName;
            this.layoutControlItem11A.CustomizationFormText = "Location";
            this.layoutControlItem11A.Location = new System.Drawing.Point(0, 258);
            this.layoutControlItem11A.Name = "layoutControlItem11A";
            this.layoutControlItem11A.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem11A.Text = "Location";
            this.layoutControlItem11A.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem11B
            // 
            this.layoutControlItem11B.Control = this.lblTotaltime;
            this.layoutControlItem11B.CustomizationFormText = "Total Time";
            this.layoutControlItem11B.Location = new System.Drawing.Point(0, 275);
            this.layoutControlItem11B.Name = "layoutControlItem11B";
            this.layoutControlItem11B.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem11B.Text = "Total Time";
            this.layoutControlItem11B.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem16
            // 
            this.layoutControlItem16.Control = this.lblKills;
            this.layoutControlItem16.CustomizationFormText = "Kills";
            this.layoutControlItem16.Location = new System.Drawing.Point(0, 292);
            this.layoutControlItem16.Name = "layoutControlItem16";
            this.layoutControlItem16.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem16.Text = "Kills";
            this.layoutControlItem16.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem17
            // 
            this.layoutControlItem17.Control = this.lblXPGained;
            this.layoutControlItem17.CustomizationFormText = "XP Gained";
            this.layoutControlItem17.Location = new System.Drawing.Point(0, 309);
            this.layoutControlItem17.Name = "layoutControlItem17";
            this.layoutControlItem17.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem17.Text = "XP Gained";
            this.layoutControlItem17.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem18
            // 
            this.layoutControlItem18.Control = this.lblXPMin;
            this.layoutControlItem18.CustomizationFormText = "XP/M";
            this.layoutControlItem18.Location = new System.Drawing.Point(0, 326);
            this.layoutControlItem18.Name = "layoutControlItem18";
            this.layoutControlItem18.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem18.Text = "XP/M";
            this.layoutControlItem18.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem19
            // 
            this.layoutControlItem19.Control = this.lblXPH;
            this.layoutControlItem19.CustomizationFormText = "XP/H";
            this.layoutControlItem19.Location = new System.Drawing.Point(0, 343);
            this.layoutControlItem19.Name = "layoutControlItem19";
            this.layoutControlItem19.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem19.Text = "XP/H";
            this.layoutControlItem19.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem20
            // 
            this.layoutControlItem20.Control = this.lblSPGained;
            this.layoutControlItem20.CustomizationFormText = "SP Gained";
            this.layoutControlItem20.Location = new System.Drawing.Point(0, 360);
            this.layoutControlItem20.Name = "layoutControlItem20";
            this.layoutControlItem20.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem20.Text = "SP Gained";
            this.layoutControlItem20.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem21
            // 
            this.layoutControlItem21.Control = this.lblSPH;
            this.layoutControlItem21.CustomizationFormText = "SP/H";
            this.layoutControlItem21.Location = new System.Drawing.Point(0, 394);
            this.layoutControlItem21.Name = "layoutControlItem21";
            this.layoutControlItem21.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem21.Text = "SP/H";
            this.layoutControlItem21.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem22
            // 
            this.layoutControlItem22.Control = this.lblSPMin;
            this.layoutControlItem22.CustomizationFormText = "SP/Min";
            this.layoutControlItem22.Location = new System.Drawing.Point(0, 377);
            this.layoutControlItem22.Name = "layoutControlItem22";
            this.layoutControlItem22.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem22.Text = "SP/Min";
            this.layoutControlItem22.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem23
            // 
            this.layoutControlItem23.Control = this.lblDied;
            this.layoutControlItem23.CustomizationFormText = "Died";
            this.layoutControlItem23.Location = new System.Drawing.Point(0, 411);
            this.layoutControlItem23.Name = "layoutControlItem23";
            this.layoutControlItem23.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem23.Text = "Died";
            this.layoutControlItem23.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem24
            // 
            this.layoutControlItem24.Control = this.lblDiedsess;
            this.layoutControlItem24.CustomizationFormText = "Diedsess";
            this.layoutControlItem24.Location = new System.Drawing.Point(0, 428);
            this.layoutControlItem24.Name = "layoutControlItem24";
            this.layoutControlItem24.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem24.Text = "Diedsess";
            this.layoutControlItem24.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem15
            // 
            this.layoutControlItem15.Control = this.lblItemDrops;
            this.layoutControlItem15.CustomizationFormText = "Drops";
            this.layoutControlItem15.Location = new System.Drawing.Point(0, 445);
            this.layoutControlItem15.Name = "layoutControlItem15";
            this.layoutControlItem15.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem15.Text = "Drops";
            this.layoutControlItem15.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem25
            // 
            this.layoutControlItem25.Control = this.lblGoldLoop;
            this.layoutControlItem25.CustomizationFormText = "Gold/Loop";
            this.layoutControlItem25.Location = new System.Drawing.Point(0, 462);
            this.layoutControlItem25.Name = "layoutControlItem25";
            this.layoutControlItem25.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem25.Text = "Gold/Loop";
            this.layoutControlItem25.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem25A
            // 
            this.layoutControlItem25A.Control = this.lblGoldPetHour;
            this.layoutControlItem25A.CustomizationFormText = "79274";
            this.layoutControlItem25A.Location = new System.Drawing.Point(0, 479);
            this.layoutControlItem25A.Name = "layoutControlItem25A";
            this.layoutControlItem25A.Size = new System.Drawing.Size(89, 17);
            this.layoutControlItem25A.Text = "Gold/H";
            this.layoutControlItem25A.TextSize = new System.Drawing.Size(54, 13);
            // 
            // layoutControlItem12
            // 
            this.layoutControlItem12.Control = this.peHPBar;
            this.layoutControlItem12.CustomizationFormText = "layoutControlItem12";
            this.layoutControlItem12.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem12.MaxSize = new System.Drawing.Size(0, 24);
            this.layoutControlItem12.MinSize = new System.Drawing.Size(24, 24);
            this.layoutControlItem12.Name = "layoutControlItem12";
            this.layoutControlItem12.Size = new System.Drawing.Size(89, 24);
            this.layoutControlItem12.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem12.Text = "HP Bar";
            this.layoutControlItem12.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem12.TextVisible = false;
            // 
            // layoutControlItem13
            // 
            this.layoutControlItem13.Control = this.peMPBar;
            this.layoutControlItem13.CustomizationFormText = "layoutControlItem13";
            this.layoutControlItem13.Location = new System.Drawing.Point(0, 24);
            this.layoutControlItem13.MaxSize = new System.Drawing.Size(0, 24);
            this.layoutControlItem13.MinSize = new System.Drawing.Size(24, 24);
            this.layoutControlItem13.Name = "layoutControlItem13";
            this.layoutControlItem13.Size = new System.Drawing.Size(89, 24);
            this.layoutControlItem13.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem13.Text = "HP Bar";
            this.layoutControlItem13.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem13.TextVisible = false;
            // 
            // layoutControlItem27
            // 
            this.layoutControlItem27.Control = this.rec;
            this.layoutControlItem27.ControlAlignment = System.Drawing.ContentAlignment.MiddleRight;
            this.layoutControlItem27.Location = new System.Drawing.Point(89, 0);
            this.layoutControlItem27.Name = "layoutControlItem27";
            this.layoutControlItem27.Size = new System.Drawing.Size(691, 496);
            this.layoutControlItem27.Text = "Log";
            this.layoutControlItem27.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem27.TextVisible = false;
            // 
            // layoutControlItem26
            // 
            this.layoutControlItem26.Control = this.beCommands;
            this.layoutControlItem26.CustomizationFormText = "Commands";
            this.layoutControlItem26.Location = new System.Drawing.Point(0, 496);
            this.layoutControlItem26.Name = "layoutControlItem26";
            this.layoutControlItem26.Size = new System.Drawing.Size(780, 34);
            this.layoutControlItem26.Text = "Commands";
            this.layoutControlItem26.TextSize = new System.Drawing.Size(54, 13);
            // 
            // BotInfoUC
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.dataLayoutControl1);
            this.Name = "BotInfoUC";
            this.Size = new System.Drawing.Size(800, 550);
            this.Load += new System.EventHandler(this.BotInfoUC_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).EndInit();
            this.dataLayoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.beCommands.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ceVisable.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.peMPBar.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.peHPBar.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGeneratedGroup0)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem9)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem11)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem14)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem11A)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem11B)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem16)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem17)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem18)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem19)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem20)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem21)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem22)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem23)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem24)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem15)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem25)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem25A)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem12)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem13)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem27)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem26)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private DevExpress.XtraDataLayout.DataLayoutControl dataLayoutControl1;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup1;
        private DevExpress.XtraEditors.LabelControl lblSkillPoint;
        private DevExpress.XtraEditors.LabelControl lblGold;
        private DevExpress.XtraEditors.LabelControl lblLevel;
        private DevExpress.XtraEditors.LabelControl lblPosY;
        private DevExpress.XtraEditors.LabelControl lblPosX;
        private DevExpress.XtraEditors.LabelControl lblConnectionQualityCur;
        private DevExpress.XtraEditors.LabelControl lblConnectionQualityAvg;
        private DevExpress.XtraEditors.LabelControl lblBotStatus;
        private DevExpress.XtraEditors.LabelControl lblSilkroadServerStatus;
        private DevExpress.XtraEditors.LabelControl lblGroup;
        private DevExpress.XtraEditors.LabelControl lblCharName;
        private DevExpress.XtraEditors.PictureEdit peMPBar;
        private DevExpress.XtraEditors.PictureEdit peHPBar;
        private DevExpress.XtraEditors.CheckEdit ceVisable;
        private DevExpress.XtraEditors.LabelControl lblSPMin;
        private DevExpress.XtraEditors.LabelControl lblSPH;
        private DevExpress.XtraEditors.LabelControl lblSPGained;
        private DevExpress.XtraEditors.LabelControl lblXPH;
        private DevExpress.XtraEditors.LabelControl lblXPMin;
        private DevExpress.XtraEditors.LabelControl lblXPGained;
        private DevExpress.XtraEditors.LabelControl lblKills;
        private DevExpress.XtraEditors.LabelControl lblTotaltime;
        private DevExpress.XtraEditors.LabelControl lblLocationName;
        private DevExpress.XtraEditors.LabelControl lblDiedsess;
        private DevExpress.XtraEditors.LabelControl lblDied;
        private DevExpress.XtraEditors.LabelControl lblGoldPetHour;
        private DevExpress.XtraEditors.LabelControl lblGoldLoop;
        private DevExpress.XtraEditors.LabelControl lblItemDrops;
        private DevExpress.XtraEditors.ButtonEdit beCommands;
        private DevExpress.XtraLayout.LayoutControlGroup autoGeneratedGroup0;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem1;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem2;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem3;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem4;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem5;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem6;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem7;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem8;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem9;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem10;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem11;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem14;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem11A;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem11B;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem16;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem17;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem18;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem19;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem20;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem21;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem22;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem23;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem24;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem15;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem25;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem25A;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem26;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem12;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem13;
        private DevExpress.XtraRichEdit.RichEditControl rec;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem27;
    }
}
